# Dockerfile

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install nodejs -yq
WORKDIR /app


# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . .
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .

# Run the app on container startup
# Use your project name for the second parameter
# e.g. MyProject.dll

# ENTRYPOINT [ "dotnet", "DataExch.dll" ]
# https://youtu.be/FUYkgikznaE
#docker build -t dataexch .
#heroku container:push -a dataexch web
#heroku container:release -a dataexch web

CMD ASPNETCORE_URLS=http://*:$PORT dotnet DataExch.dll
